[package]
name = "led-roulette"
version = "0.1.0"
authors = ["Henrik BÃ¶ving <hargonix@gmail.com>"]
edition = "2018"

[dependencies]
nrf52840-dk-bsp = "0.2.0"
cortex-m = "0.7.3"
cortex-m-rt = "0.6"
panic-halt = "0.2.0"
rtt-target = { version = "0.3.1", features = ["cortex-m"] }
panic-rtt-target = { version = "0.1.2", features = ["cortex-m"] }
